### ISSUE TITLE
MIDI over USB

### ISSUE THREAD

**Issue by artouste** [earlephilhower/arduino-pico#124]
Hello is the MIDIUSB library for RPI2040  (like MIDIUSB lib https://www.arduino.cc/en/Reference/MIDIUSB) is planned in your future developments?
thank you for your work
Phil

**Comment by earlephilhower** [comment]
Unfortunately to get MIDIUSB running would require both changes to arduino-pico (move from tinyUSB to the PluggableUSB stuff from old AVR days) and changes to the MIDIUSB library because it has a bunch if `#ifdef <BOARDTYPE>....#elif defined <BOARDTYPE>...` in it because even PluggableUSB isn't 100% compatible between different systems, anyway.  So I have to say it's a low priority for me.

If someone wants to take it up, I'd love a PR, but for me I'm looking first at implementing the HID class libraries (mouse/keyboard/gamepad).
