### ISSUE TITLE
Cannot install in platformio

### ISSUE THREAD

**Issue by Haismd03** [earlephilhower/arduino-pico#1320]
Hello everyone,
I have recently decided to rewrite my code from Arduino IDE into better form in platformio.
But I'm unable to instal this core into Platformio. It keeps returning an error over and over again.

![obrazek](https://user-images.githubusercontent.com/57405415/226409940-4f315a0c-df81-4acf-b51b-a6a963448383.png)

Is this familier to anyone? Do you know how to fix it?

**Comment by earlephilhower** [comment]
It's generally a bad idea to paste images of error messages, instead of just pasting the text.  That makes it harder to read and unsearchable.

That said, this is a known Windows problem with solution described in #1321.  Enable long paths and tell git to use them.  Then delete your current partially downloaded repo and re-install and you should be good.
