### ISSUE TITLE
Serial monitor does not show messages when on Generic RP2040

### ISSUE THREAD

**Issue by teasin951** [earlephilhower/arduino-pico#1341]
When I'm on Generic RP2040 board the serial monitor does not show anything, switching to RPi Pico fixes it. Just to point it out.

Update: I've just had the same bug but with normal RPi Pico and Pico W selected. The serial is still visible in Thonny though. Do not know what it is then.

**Comment by earlephilhower** [comment]
Sorry, this can't be reproduced here.  You may want to check your device driver settings if under Windows (see https://arduino-pico.readthedocs.io/en/latest/install.html#windows-7-driver-notes ) as sometimes Windows won't even recognize a basic driverless CDC device if there is no INF set up.

Also, with Generic RP2040 you need to manually set the flash interface speed.  Use `SPI/4` for the most compatible because if you get the flash interface wrong the RP2040 could crash while trying to read and execute the program.

Good luck!
