### ISSUE TITLE
Compile time settings on picodebug upload

### ISSUE THREAD

**Issue by hreintke** [earlephilhower/arduino-pico#1405]
Hi,

I am working on a pico w, and experimenting with hardware debugging/picoprobe.
Currently I use VisualStudio with VisulMicro as the IDE.
Have a pico w configured as picodebug and another pico w as target.

What I noticed : 

- in board.txt you have the line 
`rpipicow.menu.uploadmethod.picodebug.build.picodebugflags=-UUSE_TINYUSB -DNO_USB -DDISABLE_USB_SERIAL -I{runtime.platform.path}/tools/libpico`

- in platform.txt you have the line
`compiler.flags=-march=armv6-m -mcpu=cortex-m0plus -mthumb -ffunction-sections -fdata-sections {build.flags.exceptions} {build.flags.stackprotect} {build.flags.cmsis} {build.picodebugflags}`

That means by changing the upload method to picodebug, you update the compile flags, adding (among others) NO_USB 

But, 

- The VMicro IDE does not trigger recompile of the core after changing the upload method, don't know whether that is correct or not.

- I think you can use the USB Serial when using a usb cable to both the picodebug and the pico target. For that to work NO_USB should not be set.

**Comment by earlephilhower** [comment]
I think you're confusing pico-debug, which is a super-neat hack and uses one of the cores on the Pico and its USB interface to let you debug w/o any extra HW whatsoever, and Picoprobe which is a 2nd board connected to the SWD pins to the board-under-debug.  

I can't comment on the VMicro IDE, never seen or heard of it before, sorry.

For Picodebug, though, you DO need `-DNO_USB` because the USB port is completely controlled by the debugging core, not your app core.

For picoprobe, there's nothing special needed in terms of defines/etc. to get running.  Just make sure which version of Picoprobe (original or cmsis-dap) and use the appropriate option.

**Comment by hreintke** [comment]
OK, Understand it now. 

I was indeed not aware of the pico-debug software.
