### ISSUE TITLE
WiFi documentation question

### ISSUE THREAD

**Issue by sreimchen** [earlephilhower/arduino-pico#1523]
Maybe too early to open a issue for this but maybe someone can give me a quick answer to my following question because I'm confused:

I would like to use WiFi on both cores (MQTT client that uses the WiFi client and the CYW43 under the hood) with a mutex if necessary... but is that even possible? Or do I need to run all network functions on Core 0? When how? Are already mutexes internally used or do I need to wrap all WiFi calls within a critical section?

I'm not using FreeRTOS.

Part of the documentation at https://arduino-pico.readthedocs.io/en/latest/wifi.html:
![Screenshot_2023-06-11-20-52-08-566-edit_com.android.chrome.jpg](https://github.com/earlephilhower/arduino-pico/assets/33686223/51ea7e3b-c5e3-4436-9c47-abad48ca6ea0)

Sorry, if that is not a real issue and more of understanding of how things are meant to understand... of course I could just run some code but even then I wouldn't know for sure. 

Thanks for your time and this great project!

**Comment by earlephilhower** [comment]
No, a mutex will not let you do WiFi code on core1, at least not reliably.

You will need to use some sort of message queue from core1 to a processing loop on core0 if you want to have core1 do any WiFi (i.e. core1 can request work, but can't actually do anything).  The limitation is related to some IRQ and LWIP internals.

Alternatively, consider refactoring to have core0 be the network side of your app, while core1 does the I/O processing (I assume since it's MQTT)...
