### ISSUE TITLE
PlatformIO recursively clones the entire PicoSDK module, with its own submodules.

### ISSUE THREAD

**Issue by ProtonNumber** [earlephilhower/arduino-pico#1546]
Installing this module on platformIO causes it to clone the PicoSDK, and all submodules. 
This includes TinyUSB, which has submodules for every hal it supports, plus every possible dependency.

Amusingly this results in FreeRTOS being cloned twice.

This is a really minor issue, as it doesnt impair the functioning of the library, but it makes installation take forever.

**Comment by earlephilhower** [comment]
As we use the Pico-SDK unmodified, there's nothing to be done here about it.  The next release will have the SDK 1.5.1  which will shrink the TinyUSB install significantly.  You can (should) use the `git` version and not the Platform package as P.IO has disallowed me from publishing new versions for a couple months because they're removing all Raspberry Pi Pico support soon.  If you use `git now, you'll get that smaller install since the 1.5.1 SDK was merged here yesterday.

**Comment by ProtonNumber** [comment]
Wait, they're planning to remove pico support?

Thats a shame.

**Comment by minisbett** [comment]
What exactly do you mean by "remove pico support"?

**Comment by earlephilhower** [comment]
https://github.com/platformio/platform-raspberrypi/pull/36

**Comment by minisbett** [comment]
> [platformio/platform-raspberrypi#36](https://github.com/platformio/platform-raspberrypi/pull/36)

I read it but couldn't really understand the issue. PIO is trying to force RPi Trading to pay that they explicitly said they have no interest?

**Comment by earlephilhower** [comment]
https://github.com/platformio/platform-raspberrypi/pull/36#issuecomment-1566052525

**Comment by Ing-Dom** [comment]
> You can (should) use the `git` version and not the Platform package as P.IO has disallowed me [...]
what exactly do you mean with that and how do I do it?

Is it this what's currently marked "deprecated" ?
```
platform_packages =
maxgerhardt/framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git
maxgerhardt/toolchain-pico@https://github.com/earlephilhower/pico-quick-toolchain/
```
