### ISSUE TITLE
WiFi Connect problem

### ISSUE THREAD

**Issue by GurraE** [earlephilhower/arduino-pico#1639]
I have been doing some test with the PICO and connected LED:s, connected DS18B20:s, SH1106 OLED displays etc. and everything seems to work fine.

So now I am invoking WiFi. (WiFi.h)
Setting up a sketch with nothing else but WiFi.h (no other libraries),  works. 
(It takes a long time before the WiFi connects, during which it outputs a lot of WiFi.Status 6, but after a while it connects).

After adding the WiFi routine  to a simple sketch with a DS18B20 temp-sensor (and the standard OneWire & DallasTemperature libraries), it no longer connects to WiFi.
When I disable the  OneWire.h & DallasTemperature.h libraries, everything works again , and the WiFi connects.

This is the simplified sketch (and the platformio.ini)  that does NOT connect
**main.cpp**
`#include <Arduino.h>
#include <WiFi.h>

#include <OneWire.h>
#include <DallasTemperature.h>
#include <Wire.h>
#include <oled.h>

const char *ssid = "XXX";
const char *password = "xxxxx";

void setup()
{
  delay(10000); // Delay before
  Serial.begin(115200);
  WiFi.mode(WIFI_STA); // Optional
  WiFi.setTimeout(20000);
  WiFi.begin(ssid, password);
  Serial.println("\nConnecting");

  while (WiFi.status() != WL_CONNECTED)
  {
    Serial.print(".");
    delay(500);
    // Serial.print(WiFi.status());
  }

  Serial.println("\nConnected to the WiFi network");
  Serial.print("Local PICO IP: ");
  Serial.println(WiFi.localIP());
}

void loop()
{
}`

**platformio.ini**
`[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m

[env:UNIT29-rpipicow]
board = rpipicow
upload_port = COM20
monitor_port = COM20
monitor_speed = 115200

lib_deps =
  ${env.lib_deps}
  https://github.com/PaulStoffregen/OneWire.git  
  https://github.com/milesburton/Arduino-Temperature-Control-Library.git
  durydevelop/OLED SSD1306 - SH1106@^1.0.7`

So if I disable the OneWire.h and DallasTemperature.h lines at the top, the WiFi connects...........

In the complete sketch (with functions for displaying Temperatures etc.), using the same libraries, all temperatures are displayed ok.

Is this a known problem ??

**Comment by earlephilhower** [comment]
Unable to reproduce here using the Arduino Library Manager installs for OneWire and DallasTemperature.  I have no id3ea what the OLED library you're using, nothing shows up like it in the Arduino Lib Manager.

Note that OneWire throws warnings that it's not ported and will use slow `digitalWrite`, etc.

Also, including a header file alone should have no impact on the code generated, unless the header actually defines functions that are linked in (generally a bad idea and I hope nobody's doing that!).

Maybe you're having trouble with your WiFi connection and you end up getting add'l noise in your system because you're doing something with the Pico pins.

In any case there's nothing in the core dealing w/the actual WiFi stack (that's all in the binary blob for the CYW43) so there's nothing for us to do here.

My own test, always connects with 12 does (6 seconds):
````
#include <Arduino.h>
#include <WiFi.h>
/*
#include <oled.h>
*/

#include <DallasTemperature.h>
#include <OneWire.h>
#include <Wire.h>

const char *ssid = "xxx";
const char *password = "xxx";

void setup()
{
delay(10000); // Delay before
Serial.begin(115200);
WiFi.mode(WIFI_STA); // Optional
WiFi.setTimeout(20000);
WiFi.begin(ssid, password);
Serial.println("\nConnecting");

while (WiFi.status() != WL_CONNECTED)
{
Serial.print(".");
delay(500);
// Serial.print(WiFi.status());
}

Serial.println("\nConnected to the WiFi network");
Serial.print("Local PICO IP: ");
Serial.println(WiFi.localIP());
}

void loop()
{
}




Connecting
.............
Connected to the WiFi network
Local PICO IP: 192.168.1.131

Connecting
............
Connected to the WiFi network
Local PICO IP: 192.168.1.131

Connecting
............
Connected to the WiFi network
Local PICO IP: 192.168.1.131


````
