### ISSUE TITLE
Printing a zero value uint64_t number fails.

### ISSUE THREAD

**Issue by greiman** [earlephilhower/arduino-pico#1691]
Here is a test case:
```
void setup() {
  Serial.begin(9600);
  while (!Serial) {}
  uint64_t n = 123;
  uint64_t m = n;
  Serial.print("n - m = ");
  Serial.println(n - m);
  n++;
  Serial.print("n - m = ");
  Serial.println(n - m);
}
void loop() {}
```

The output is:

> n - m = 
> n - m = 1

The problem is in printULLNumber [here](https://github.com/earlephilhower/ArduinoCore-API/blob/e37df85425e0ac020bfad226d927f9b00d2e0fb7/api/Print.cpp#L367)

I can see how zero fails but am not sure of the best fix.

Probably the while needs to be a do while loop.

**Comment by earlephilhower** [comment]
Can you give an MCVE?  It works fine as far as I can tell:

````
void setup() {
}
uint64_t uz = 0;
void loop() {
    Serial.printf("%" PRIu64 "\n", uz);
    delay(500);
}
````
gives
````
0
0
0
...
````

**Comment by greiman** [comment]
Sorry, I accident hit comment too soon.  see the above example.

**Comment by earlephilhower** [comment]
Ah, thanks.  Arduino reinventing `vfprintf` and not actual `printf` which makes sense (the `Serial.printf` bit is handled by Newlib which I'm sure is good).

You might want to push this upstream to the main [ArduinoCore-API repo](https://github.com/arduino/ArduinoCore-API) since this is untouched Arduino.cc code.

**Comment by earlephilhower** [comment]
https://github.com/arduino/ArduinoCore-API/issues/178

Already opened 9 months ago.
