### ISSUE TITLE
More space for emulated EEPROM

### ISSUE THREAD

**Issue by CaptainCredible** [earlephilhower/arduino-pico#2072]
Currently the maximum amount of space that can be allocated for the included EEPROM library is 4096 bytes. The flash storage has a lot of space though, and it would be very useful to be able to use more of this space for pretend EEPROM.

Also the EEPROM examples warn that the flash memory will perform worse with regards to write cycles than a proper EEPROM. The datasheet for the onboard flash memory boasts:
– Min. 100K Program-Erase cycles per sector
– More than 20-year data retention

Am I misunderstanding what this means?

**Comment by earlephilhower** [comment]
Don't use `EEPROM` for new code, it's very much obsolete and basic.  The RPI boards probably use great flash with those specs, but there are RP2040-based boards from AliExpress with much less lifetime and quality flash.

Use `LittleFS` and then you can make files as large or small as needed, and they will be wear-leveled across the entire flash space.  That would make even junky flash thousands of times better.  You can also do things like ping-pong files so that if you lose power in the middle of writing new data you would still be able to get the old data on restart.
