### ISSUE TITLE
Wifi multi ignores WDT - side quest: would be nice to detect if WDT enabled

### ISSUE THREAD

**Issue by tyeth** [earlephilhower/arduino-pico#2684]
Hey Earle 👋 
We're using the wifi multi class to connect, but I've read the watchdog timers maximum period is ~8.3s, which is less than my wifi takes to finish the connection (about 15s) - is it a mesh/wifi6-mesh-router combo, yes, and it should be amazing but often sucks.

Calling wifiMulti.run(20000) would be enough, but we enable the watchdog timer earlier on, which I've now changed, but if disconnected later then the watchdog will be active and reconnects may trip the watchdog (a reset then is fine to be honest).

Long story short we can't have the watchdog enabled and use wifi multi to connect with a timeout above 8seconds, due to wifi multi not being watchdog aware and not feeding the watchdog. This might be intended/expected, but I certainly didn't expect it 😁 

 I wonder if you might be able to make wifi multi feed the watchdog if enabled, and as a side quest / yak shaving mission also add a function to return if the watchdog is enabled (although maybe that's unnecessary as it appears there is a function to return the time remaining - [which in rp2040 really returns the initial time set not remaining](https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_watchdog/include/hardware/watchdog.h#L128) so maybe that would be the thing to use - assuming it's 0 at power on with wdt initially disabled).

**Comment by earlephilhower** [comment]
Sorry, but this is by design and not something I think should be changed.  Once you enable WDT lots of things become dangerous, and this is just one of them.  Having it actually feed the WDT behind the scenes doesn't seem like it would be the right thing to do for everyone, always, since WDT is most definitely not standard operating procedure.  If you're doing WDT then you'll have to do your own WiFi connection process...

**Comment by tyeth** [comment]
You're a beauty, thanks Earle, confirmed my own thoughts, really appreciate the steer.
