### ISSUE TITLE
Can't find interface/picoprobe.cfg

### ISSUE THREAD

**Issue by flyrainning** [earlephilhower/arduino-pico#339]
platformio.ini
```
[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino

build_board.core = earlephilhower
board_build.filesystem_size = 1m

platform_packages =
  maxgerhardt/framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git
  maxgerhardt/toolchain-pico@https://github.com/earlephilhower/pico-quick-toolchain/releases/download/1.3.1-a/x86_64-linux-gnu.arm-none-eabi-7855b0c.210706.tar.gz

upload_protocol = picoprobe
```
---

output:

```
Building in release mode
Retrieving maximum program size .pio/build/pico/firmware.elf
Flash size: 2.00MB
Sketch size: 1.00MB
Filesystem size: 1.00MB
Maximium size: 1044480 Flash Length: 1044480 EEPROM Start: 270528512 Filesystem start 269479936 Filesystem end 270528512
Checking size .pio/build/pico/firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  18.6% (used 50260 bytes from 270336 bytes)
Flash: [=         ]   7.0% (used 72740 bytes from 1044480 bytes)
Configuring upload protocol...
AVAILABLE: cmsis-dap, jlink, picoprobe, picotool, raspberrypi-swd
CURRENT: upload_protocol = picoprobe
Uploading .pio/build/pico/firmware.bin
Open On-Chip Debugger 0.11.0+dev-gec0240e6a-dirty (2021-03-09-09:49)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
debug_level: 1

embedded:startup.tcl:26: Error: Can't find interface/picoprobe.cfg
in procedure 'script' 
at file "embedded:startup.tcl", line 26
*** [upload] Error 1
```

**Comment by maxgerhardt** [comment]
1. debugging does not yet work because of probably linker issues per https://github.com/earlephilhower/arduino-pico/issues/66#issuecomment-894785078
2. you did not add tool-openocd in `platform_packages` as I did in [my example](https://github.com/maxgerhardt/pio-pico-core-earlephilhower-test/blob/ad342fd984696139a931f73be991e85e9855040e/platformio.ini#L46-L49).

**Comment by flyrainning** [comment]
Sorry,I am bad at English.
1. I'm not debugging,just uploading..and I found the problem in my platformio.ini,I copy platformio.ini from [docs examples](https://arduino-pico.readthedocs.io/en/latest/platformio.html#examples)
but the docs's examples has a problem at `build_board.core = earlephilhower` .it should be `board_build`

2. thanks for your platform_packages example.but I'm using ubuntu ,not windows.I build openocd for linux myself and put it to gitee.com .It works fine [openocd for linux](https://gitee.com/flyboard2040/pio-openocd-picoprobe-linux.git)

there is my platformio.ini and it's works fine so far
```
[env:pico_earlephilhower]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino

board_build.core = earlephilhower
board_build.filesystem_size = 1m
board_build.f_cpu = 133000000L

lib_ldf_mode = chain+

platform_packages =
  maxgerhardt/framework-arduinopico@https://gitee.com/flyboard2040/arduino-pico.git
  maxgerhardt/toolchain-pico@https://github.com/earlephilhower/pico-quick-toolchain/releases/download/1.3.1-a/x86_64-linux-gnu.arm-none-eabi-7855b0c.210706.tar.gz
  platformio/tool-openocd-raspberrypi@https://gitee.com/flyboard2040/pio-openocd-picoprobe-linux.git

upload_protocol = picoprobe
debug_tool = picoprobe
```

3. there is a new problem.I create a new board named flyboard2040,and added to the arduino-pico framework.It's works at Arduino IDE,but how to change the board in platformio.ini ? when i change the line `board = pico` there is an Error `Error: Unknown board ID 'xxxxxx'`

Thanks

**Comment by maxgerhardt** [comment]
1. You are correct, there is a typo, this is fixed in https://github.com/earlephilhower/arduino-pico/pull/342
2. Exactly, the package is pre-built for Linux, but it looks like you have created the needed package successfully.
3. If you want to create a new board you should create a new folder `boards/` in the root of the project. If you  want to be able to say `board = flyboard2040`, you need to create the file `boards/flyboard2040.json`. The contents of the board manifest should be derived from [`pico.json`](https://github.com/maxgerhardt/platform-raspberrypi/blob/develop/boards/pico.json) with changes for your particular board.

**Comment by flyrainning** [comment]
it works,thanks
