### ISSUE TITLE
Error uploading: No drive to deploy

### ISSUE THREAD

**Issue by technoblogy** [earlephilhower/arduino-pico#5]
My application compiles successfully, apart from five warnings:

    /Users/david/Library/Arduino15/packages/rp2040/tools/pqt-gcc/1.0.1-base-3a57aed/bin/../lib/gcc/arm-none-eabi/
    10.2.0/../../../../arm-none-eabi/bin/ld: warning: changing start of section .bss by 4 bytes

But then the upload fails with:

    Converting to uf2, output size: 516096, start address: 0x2000
    No drive to deploy.
    An error occurred while uploading the sketch

I was able to successfully upload your **Fade** example. Any suggestions?

**Comment by earlephilhower** [comment]
That warning is fine, it's just the linker being chatty.  No worries there.

It seems the UF2 drive didn't get mounted by the OS.

Since the reboot-to-UF2 is actually SW controlled (via SW controlled USB), if there's a hard crash in the Pico, it won't work.  In that case, just reconnect the USB cable while holding down BOOTSEL to ensure the ROM itself enters the upload state.

Macs are also a little tricky w/the serial port controls changing between OS releases.  #2 was able to get things running find, but did not report his OS level.

Another possibility is that the Mac isn't mounting the UF2 volume automatically.  To fix that, I'd need a Mac user's help as it's out of my cross-compiling domain.  There may be a setting in the OS about mounting USB sticks automatically, or there may be a CLI command that can cause MacOS to mount things.  Under Windows and Linux it "just works" so there's nothing special there.

**Comment by technoblogy** [comment]
OK, I can now get the upload to work if I unplug and then plug back in with the BOOTSEL button held down.

I now don't seem to be able to get any output on the Arduino Serial Monitor. For example, running your example eeprom_write.

I'm on Mac.

**Comment by earlephilhower** [comment]
Macs and serial ports always seem to be troublesome. :(  Some of the same issues were seen on the ESP8266 Arduino port https://github.com/esp8266/Arduino

Do you have the proper port selected in the Arduino menus?  (Would also affect the auto-reset...)

![image](https://user-images.githubusercontent.com/11875/112212706-8b3b9000-8bda-11eb-91fe-c73d9ee87429.png)

You can use the `screen` command line tool to check comms.  Close the Arduino serial monitor and then from the command line use `screen /dev/ttyXXXX` where the TTYxxxx is the path shown from the menu.

**Comment by technoblogy** [comment]
Yes I think so:

<img width="751" alt="Screen Shot 2021-03-23 at 21 06 04 copy" src="https://user-images.githubusercontent.com/22325291/112218641-dc1fa880-8c1b-11eb-82b3-81756624c326.png">

**Comment by technoblogy** [comment]
Closing because there is another issue about the Serial output.

**Comment by me912** [comment]
I found the solution. Firstly, you push bootsel button and go to arduino ide download upload your code to board and it work.

**Comment by odehjoyce** [comment]
I have tried all the solutions stated here and it doesn't work. I am using a windows os

**Comment by odehjoyce** [comment]
Finally solved it. Thanks

**Comment by smarttech24** [comment]
> I have tried all the solutions stated here and it doesn't work. I am using a windows os

how you solve that
