### ISSUE TITLE
Slower compile and upload Arduino 2.0.0rc5

### ISSUE THREAD

**Issue by Gavin-Perry** [earlephilhower/arduino-pico#523]
Great work Earl! Thanks for doing this (support PICO on Arduino and PlatformIO).
I use:
Arduino IDE 2.0.0rc5, Windows 11, SSD hard drive on Aspire 5

So this should be fast and with earlier version (rc3 or 1.8x maybe, and different pico I think) it was fast.

Now when I compile/upload not only does it take a longish time (up to a minute) it also gives feedback in a different order.
1 output screen (black one at the bottom) goes blank
2  D: drive pops up ready for the UF@ file
3  File loads and drive closes
4 Done compiling message
5 Warning/error about COM reset issue (which used to make it totally fail but now works again)
6 Done uploading message
It used to be 3 comes before 2 in the list above. Now 4 comes before 3 sometimes.
Any ideas? Does it have anything to do with the PICO tool chain you use? Has that changed?
What is the schedule for 2.0 final?
Anything I can do to speed things up again?
Any easy way to use 1.8 and 2.0 on the same computer? They seem to conflict with each other and it's a big struggle (re-install, delete pref files...)  I have different directories for each environment but they both want to use ../local/../ARDUINO15

**Comment by earlephilhower** [comment]
Sorry, again I'm unable to reproduce anything like your description. FWIW the "done compiling" bit really needs to be finalized before the "drive appears and upload" bit or else, well, what is it going to upload?  Speculative firmware? :)

As for speed, since they have moved from java to Node.js the IDE memory and CPU requirements just to show the editor are probably 2x or 4x higher.  All the eye candy doesn't come free, especially since they're working in JavaScript(!).  It seems about the same for me on my Ryzen 5600X under Linux as the Java IDE.

Like in #518, I think you need to look at the arduino.cc forums of their bug tracker here on GitHub to get help.
