### ISSUE TITLE
CI Broken

### ISSUE THREAD

**Issue by maxgerhardt** [earlephilhower/arduino-pico#562]
Per https://github.com/earlephilhower/arduino-pico/runs/6204808142?check_suite_focus=true

```
  /usr/bin/git submodule sync --recursive
  /usr/bin/git -c protocol.version=2 submodule update --init --force --depth=1 --recursive
[...]
  Submodule 'lwip' (https://git.savannah.nongnu.org/git/lwip.git) registered for path 'pico-extras/lib/lwip'
  Cloning into '/home/runner/work/arduino-pico/arduino-pico/pico-extras/lib/lwip'...
  Error: error: Server does not allow request for unadvertised object c385f31076b27efb8ee37f00cb5568783a58f299
  Error: fatal: Fetched in submodule path 'pico-extras/lib/lwip', but it did not contain c385f31076b27efb8ee37f00cb5568783a58f299. Direct fetching of that commit failed.
  Error: fatal: Failed to recurse into submodule path 'pico-extras'
  Error: The process '/usr/bin/git' failed with exit code 128
```

seems to be upstream bug that they don't wanna fix: https://github.com/raspberrypi/pico-extras/issues/33

**Comment by earlephilhower** [comment]
Yeah, it's kind of stuck that way since right after I started the repo.  Actual CI is fine and does individual updated on the repos it needs (not recursive) but the `GH deploy pages` one seems to do a full clone.

Easy solution is for me to fork the pico-extras and adjust the LWIP repo (but TBH the official savannah... LWIP repo seems a little flaky on the ESP8266 and seems to go down once a month or so).

Long-term solution is to rewrite the I2S (and remove pico-extras) which I started doing, but got distracted by FreeRTOS.
