### ISSUE TITLE
Missing attachInterruptParam definition

### ISSUE THREAD

**Issue by marc0777** [earlephilhower/arduino-pico#601]
I was trying to us an interrupt service routine with a parameter, but I noticed that this core doesn't seem to implement `attachInterruptParam`.

A minimal setup to replicate this is:

```C++
#define INT_PIN 5

void isr(String* out) {
  Serial.println(*out);
}

void setup() {
  pinMode(INT_PIN, INPUT);
  String str = "hello";
  attachInterrupt(digitalPinToInterrupt(INT_PIN), isr, RISING, &str);
}

void loop() {
  
}
```

Compilations leads to this linker error:
```
packages\rp2040\hardware\rp2040\2.0.2\cores\rp2040/api/Interrupts.h:39: undefined reference to `attachInterruptParam'
```

Would it be possibile to implement this?

Marco

**Comment by earlephilhower** [comment]
Your example has a problem.  You can't actually pass in a stack local param (`&str`) to the callback because it won't exist after `setup()` runs.

PR #602 has been tested with an internal loopback test which moves the `String` to a global so it will exist when the callback happens and generates the interrupts in the core itself:
````
#define INT_PIN 5

void isr(String* out) {
  Serial.println(*out);
}

String str = "hello";

void setup() {
  digitalWrite(INT_PIN, LOW);
  pinMode(INT_PIN, OUTPUT);
  attachInterrupt(digitalPinToInterrupt(INT_PIN), isr, RISING, &str);
}

void loop() {
  digitalWrite(INT_PIN, LOW);
  delay(100);
  digitalWrite(INT_PIN, HIGH);
  delay(100);
}
````
