### ISSUE TITLE
RTClib/BusIO unable to detect I2C device with ItsyBitsy board

### ISSUE THREAD

**Issue by AcThPaU** [earlephilhower/arduino-pico#760]
ItsyBitsy board has I2C muxed to GPIO 2 and 3.

RTClib and BusIO cannot detect DS3231 connected to I2C.

The hardware setup works fine in CircuitPython.

**Comment by earlephilhower** [comment]
You have provided no code or MCVE, so there's not much to go on.

That said, GPIO2/3 is connected to the **second** I2C port on the RP2040, `Wire1`.  Make sure your code is using `Wire1` instead of `Wire`.  See the diagram below which shows the possible I/O muxings:
![image](https://user-images.githubusercontent.com/11875/184714865-3c5d0913-b381-4d07-b0a1-fb24d1726f50.png)

You can be even more explicit by calling
````
Wire1.setSDA(2);
Wire1.setSCL(3);
Wire1.begin(...
````

**Comment by AcThPaU** [comment]
It's very easy to reproduce. 

```
#include "RTClib.h"

RTC_DS3231 rtc;

void setup() {

Serial.begin(115200);

if (! rtc.begin()) {
 Serial.println("Couldn't find RTC");
 while(1);
 }
}
```

The problem is that RTClib does not allow you to set specific I2C bus.

**Comment by AcThPaU** [comment]
It turns out you can set I2C bus in RTClib

```
#include "RTClib.h"
#include <Wire.h>

RTC_DS3231 rtc;

void setup() {

Serial.begin(115200);
Wire1.setSDA(2);
Wire1.setSCL(3);
Wire1.begin();
if (! rtc.begin(&Wire1)) {
 Serial.println("Couldn't find RTC");
 while(1);
 }
}
```

This works, but rtc.begin() should have worked.
