### ISSUE TITLE
ISO C++ forbids converting a string constant to 'char*' 

### ISSUE THREAD

**Issue by JohnInWales** [earlephilhower/arduino-pico#78]
I don't know if this is a bug, or if you have done it by the book when no one else does, but I get a warning when using string arrays.

This is the example sketch from https://www.arduino.cc/reference/en/language/variables/data-types/string/ :

char *myStrings[] = {"This is string 1", "This is string 2", "This is string 3",
                     "This is string 4", "This is string 5", "This is string 6"
                    };

void setup() {
  Serial.begin(9600);
}

void loop() {
  for (int i = 0; i < 6; i++) {
    Serial.println(myStrings[i]);
    delay(500);
  }
}

Compiling it produces a list of warnings like this:
**/home/pi/Arduino/sketch_apr05a/sketch_apr05a.ino:1:22: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
    1 | char *myStrings[] = {"This is string 1", "This is string 2", "This is string 3",
      |                      ^~~~~~~~~~~~~~~~~~**

It does upload and run though. I've tried compiling it for Arduino, ESP-32 and Seeeduino SAMD boards, and none of them produce a warning.

**Comment by earlephilhower** [comment]
This is a legitimate warning on the Pico.  Because compiled strings are stored in XIP flash, they are most definitely not writable.  The `const` really should be there on this architecture as we don't do writable strings.  I think, for example, on the ESP32 strings are copied to RAM so you could, theoretically, write to them (but it would be frowned upon in CompSci circles, I imagine).  Same for the old-time AVRs.

We're using `gnu++17` and `gnu17` which are standard C++ and C -17 with the GNU extensions.

As it's a warning you can ignore it and as long as you don't actually try and write, it will be fine.

Good luck!
